AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Bedrock Security Controls - Comprehensive security implementation including network infrastructure, IAM, monitoring, and guardrails'

# =========================================================================
# PARAMETERS
# =========================================================================
# These parameters make the template configurable for different deployments
Parameters:
  # Network parameters
  ExistingVpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID of the existing VPC to use for VPC endpoints
    
  ExistingSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: ID of the existing subnet to use for VPC endpoints
    
  VpcCidr:
    Type: String
    Description: CIDR range for VPC ingress rule
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    ConstraintDescription: Must be a valid CIDR range

  # Administrative parameters
  AdminEmail:
    Type: String
    Description: Email address for notifications and alerts
    ConstraintDescription: Must be a valid email address
  
  MonthlyBudgetAmount:
    Type: Number
    Description: Monthly budget limit for Bedrock in USD
    MinValue: 1
    ConstraintDescription: Must be a positive number
    
  EnvironmentName:
    Type: String
    Description: Environment name (dev, test, prod, etc.)
    AllowedPattern: "[a-zA-Z0-9]+"
    ConstraintDescription: Environment name must contain only alphanumeric characters

# =========================================================================
# RESOURCES
# =========================================================================
Resources:
  # =========================================================================
  # NETWORK INFRASTRUCTURE
  # =========================================================================
  BedrockSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Bedrock endpoint - restricts network traffic
      VpcId: !Ref ExistingVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref VpcCidr
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub 'bedrock-sg-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName

  BedrockVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.bedrock-runtime'
      VpcEndpointType: Interface
      VpcId: !Ref ExistingVpcId
      SubnetIds:
        - !Ref ExistingSubnetId
      SecurityGroupIds:
        - !Ref BedrockSecurityGroup
      PrivateDnsEnabled: false
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  # =========================================================================
  # IAM ROLES AND POLICIES
  # =========================================================================
  # These resources create IAM role and policy with least privilege access to AWS Bedrock
  # following security best practices by limiting access to only required models
  # and enforcing environment-based tagging
  
  BedrockAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'bedrock-access-role-${EnvironmentName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref BedrockRestrictedPolicy
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  # Policy that restricts which Bedrock models can be accessed and enforces tagging
  BedrockRestrictedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub 'bedrock-restricted-policy-${EnvironmentName}'
      Description: Restricted policy for AWS Bedrock access with least privilege principles
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - bedrock:InvokeModel
              - bedrock:InvokeModelWithResponseStream
            Resource:
              - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-sonnet-20240229-v1:0'
              - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.titan-text-express-v1'
            Condition:
              StringEquals:
                'aws:RequestTag/Environment': !Ref EnvironmentName
          - Effect: Allow
            Action:
              - bedrock:GetFoundationModel
            Resource: '*'

  # =========================================================================
  # MONITORING AND ALERTING
  # =========================================================================
  # These resources create comprehensive monitoring and alerting for Bedrock usage
  # to enable visibility into model usage patterns, costs, and potential issues

  # Centralized log group for Bedrock model invocations
  BedrockLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/bedrock/model-invocations-${EnvironmentName}'
      RetentionInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  # SNS topic for sending alerts and notifications about Bedrock usage
  BedrockAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'bedrock-alerts-${EnvironmentName}'
      Subscription:
        - Protocol: email
          Endpoint: !Ref AdminEmail
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  # =========================================================================
  # COST MANAGEMENT
  # =========================================================================
  # These resources implement budget controls to prevent unexpected Bedrock costs
  # and provide proactive cost management and alerts when approaching thresholds

  # Monthly budget for Bedrock usage with alerts
  BedrockBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: !Sub 'bedrock-monthly-budget-${EnvironmentName}'
        BudgetType: COST
        TimeUnit: MONTHLY
        BudgetLimit:
          Amount: !Ref MonthlyBudgetAmount
          Unit: USD
        CostFilters:
          Service:
            - Amazon Bedrock
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 80
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref AdminEmail

  # =========================================================================
  # BEDROCK GUARDRAILS
  # =========================================================================
  # These resources have been moved to a separate template (bedrock-guardrail.yaml)
  # Import the guardrail ID using:
  # !ImportValue bedrock-guardrail-dev-BedrockGuardrailId

# =========================================================================
# OUTPUTS
# =========================================================================
# These outputs export important resource identifiers for cross-stack references
Outputs:
  # Network Outputs
  BedrockSecurityGroupId:
    Description: ID of the security group created for Bedrock endpoint
    Value: !Ref BedrockSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-BedrockSecurityGroupId'

  BedrockVPCEndpointId:
    Description: ID of the Bedrock VPC endpoint
    Value: !Ref BedrockVPCEndpoint
    Export:
      Name: !Sub '${AWS::StackName}-BedrockVPCEndpointId'

  BedrockVPCEndpointDNS:
    Description: DNS entries for the VPC endpoint
    Value: !Select [0, !GetAtt BedrockVPCEndpoint.DnsEntries]
    Export:
      Name: !Sub '${AWS::StackName}-BedrockVPCEndpointDNS'

  # Security Controls Outputs
  BedrockAccessRoleARN:
    Description: ARN of the Bedrock access role with least privilege permissions
    Value: !GetAtt BedrockAccessRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BedrockAccessRoleARN'

  BedrockAlertsTopicARN:
    Description: ARN of the Bedrock alerts SNS topic for monitoring notifications
    Value: !Ref BedrockAlertsTopic
    Export:
      Name: !Sub '${AWS::StackName}-BedrockAlertsTopicARN'
