AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Bedrock Network Infrastructure - VPC Endpoint and Security Group setup'

Parameters:
  ExistingVpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID of the existing VPC to use for VPC endpoints
    
  ExistingSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: ID of the existing subnet to use for VPC endpoints
    
  EnvironmentName:
    Type: String
    Description: Environment name (dev, test, prod, etc.)
    Default: dev
    AllowedPattern: "[a-zA-Z0-9]+"
    ConstraintDescription: Environment name must contain only alphanumeric characters

  VpcCidr:
    Type: String
    Description: CIDR range for VPC ingress rule
    Default: 10.0.0.0/16
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    ConstraintDescription: Must be a valid CIDR range

Resources:
  BedrockSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Bedrock endpoint - restricts network traffic
      VpcId: !Ref ExistingVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref VpcCidr
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub 'bedrock-sg-${EnvironmentName}'
        - Key: Environment
          Value: !Ref EnvironmentName

  BedrockVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.bedrock-runtime'
      VpcEndpointType: Interface
      VpcId: !Ref ExistingVpcId
      SubnetIds:
        - !Ref ExistingSubnetId
      SecurityGroupIds:
        - !Ref BedrockSecurityGroup
      PrivateDnsEnabled: false
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

Outputs:
  BedrockSecurityGroupId:
    Description: ID of the security group created for Bedrock endpoint
    Value: !Ref BedrockSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-BedrockSecurityGroupId'

  BedrockVPCEndpointId:
    Description: ID of the Bedrock VPC endpoint
    Value: !Ref BedrockVPCEndpoint
    Export:
      Name: !Sub '${AWS::StackName}-BedrockVPCEndpointId'

  BedrockVPCEndpointDNS:
    Description: DNS entries for the VPC endpoint
    Value: !Select [0, !GetAtt BedrockVPCEndpoint.DnsEntries]
    Export:
      Name: !Sub '${AWS::StackName}-BedrockVPCEndpointDNS' 